version: '3'
services:
    db:
        image: 'postgres:latest'
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: knowledge
        volumes:
          - ./pgdata:/var/lib/postgresql/data
        ports:
          - "5432:5432"
    
    mongodb:
        image: 'mongo:latest'
        restart: always
        container_name: mongo-test
        ports:
          - "27017:27017"
        volumes:
          - ./mongodata:/var/lib/mongodb/data
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: knowledge_stats